// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarEcharts: typeof import('./src/components/echarts/barEcharts.vue')['default']
    Editor: typeof import('./src/components/markdown/editor.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    PieEcharts: typeof import('./src/components/echarts/pieEcharts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WangEditor: typeof import('./src/components/wangEditor/wangEditor.vue')['default']
    XlAside: typeof import('./src/components/home/xl-aside.vue')['default']
    XlButton: typeof import('./src/components/global/form/xl-button.vue')['default']
    XlHistorylink: typeof import('./src/components/home/xl-historylink.vue')['default']
    XlInput: typeof import('./src/components/global/form/xl-input.vue')['default']
    XlLink: typeof import('./src/components/global/form/xl-link.vue')['default']
    XlNavbar: typeof import('./src/components/home/xl-navbar.vue')['default']
    XlNotification: typeof import('./src/components/home/xl-notification.vue')['default']
  }
}
