// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EchartsBarEcharts: typeof import('./../../src/components/echarts/barEcharts.vue')['default']
    EchartsPieEcharts: typeof import('./../../src/components/echarts/pieEcharts.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    GlobalFormXlButton: typeof import('./../../src/components/global/form/xl-button.vue')['default']
    GlobalFormXlInput: typeof import('./../../src/components/global/form/xl-input.vue')['default']
    GlobalFormXlLink: typeof import('./../../src/components/global/form/xl-link.vue')['default']
    HomeXlAside: typeof import('./../../src/components/home/xl-aside.vue')['default']
    HomeXlHistorylink: typeof import('./../../src/components/home/xl-historylink.vue')['default']
    HomeXlNavbar: typeof import('./../../src/components/home/xl-navbar.vue')['default']
    HomeXlNotification: typeof import('./../../src/components/home/xl-notification.vue')['default']
    MarkdownEditor: typeof import('./../../src/components/markdown/editor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WangEditorEditor: typeof import('./../../src/components/wangEditor/editor.vue')['default']
  }
}
